name: outfits
region: nyc3
services:
  - name: web-app
    image:
      registry_type: DOCKER_HUB
      registry: docker.io
      repository: jl8059/web-app
      tag: latest
    envs:
      - key: MONGO_URI
        value: mongodb://root:secret@mongodb:27017/
    http_port: 5000
    routes:
      - path: /

  - name: mongodb
    image:
      registry_type: DOCKER_HUB
      registry: docker.io
      repository: jl8059/mongodb
      tag: latest
    routes:
      - path: /mongodb