version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db

  web-app:
    build:
      context: .
    container_name: flask-app
    environment:
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    ports:
      - "5002:5000"
    depends_on:
      - mongodb
    volumes:
      - ./web-app/images:/app/images 

volumes:
  mongodb-data:
