name: MongoDB CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build MongoDB Docker Image
        run: |
          docker build -t nataliovcharov/mongodb ./mongodb

      # Push the Docker image to Docker Hub
      - name: Push MongoDB Docker Image
        run: |
          docker push nataliovcharov/mongodb

