name: MongoDB Workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "MONGO_URI=mongodb://localhost:27017" >> .env
        echo "DB_NAME=bookkeeping" >> .env
    
    - name: Run tests with coverage
      run: |
        pytest test/test_mongodb.py --cov=mongodb --cov-report=term-missing